import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/"> Buzu</Link>
        </h1>

        <p className={styles.description}>An awesome app!</p>

        <div className={styles.grid}>
          <a
            href="https://www.linkedin.com/company/buzu-brasil/about/"
            className={styles.card}
          >
            <h2>Linkedin &rarr;</h2>
            <p>Find us in linkedin</p>
          </a>

          <a href="https://github.com/BuzuBR" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Find us in Github</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
